---
# tasks file for aws_ec2_instance

  - name: Gather information about all instances
    amazon.aws.ec2_instance_info:
    register: instances

  - debug: msg="{{ instances }}"

  - debug: 
    #  msg: "{{ item.tags | regex_search('Name') }}:{{ item.state | regex_search('name') }}"
      msg: "{{ item }}"
    with_items: instances.instances
    register: current

  - debug: msg="{{ current }}"

#  - name: Deploy ec2 instance
#    amazon.aws.ec2_instance:
#      key_name: "{{ key_name }}"
#      security_group: "{{ security_group }}"
#      instance_type: "{{ instance_type }}"
#      image_id: "{{ image_id }}"
#      wait: true
#      region: "{{ region }}"
#      vpc_subnet_id: "{{ vpc_subnet_id }}"
#      network:
#        assign_public_ip: "{{ assign_public_ip }}"
#      name: "{{ instance_name }}"
#      count: 1
