---
# tasks file for aws_ec2_instance
  - name: Deploy ec2 instance
    amazon.aws.ec2_instance:
      key_name: "{{ key_name }}"
      group: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: true
      region: "{{ region }}"
      vpc_subnet_id: "{{ subnet }}"
      assign_public_ip: yes
      count: "{{ count }}"
