---
# tasks file for aws_ec2_instance

  - name: Gather information about all instances
    amazon.aws.ec2_instance_info:
      filters:
        "tag:Name": "{{ instance_name }}"
        instance-state-name: ["running", "pending", "shutting-down", "stopping", "stopped"]
    register: state

  - debug: msg="{{ state }}"

  - name: "Deploy instance {{ instance_name }}"
    amazon.aws.ec2_instance:
      key_name: "{{ key_name }}"
      security_group: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ image_id }}"
      wait: true
      region: "{{ region }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      network:
        assign_public_ip: "{{ assign_public_ip }}"
      name: "{{ instance_name }}"
      count: 1
    when: state.instances | length == 0
