---
# tasks file for aws_ec2_instance
  - name: Deploy ec2 instance
    amazon.aws.ec2_instance:
      key_name: "{{ key_name }}"
      security_group: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ image_id }}"
      wait: true
      region: "{{ region }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      network:
        assign_public_ip: "{{ assign_subnet_id }}"
      count: 1
